export type SceneWorldItem = {
  id: string;
  scene: number;
  type: "text" | "card";
  title: string;
  eyebrow?: string;
  body?: string;
  footerLeft?: string;
  footerRight?: string;
  emphasis?: "accent" | "accent2" | "neutral";
  x: number;
  y: number;
  z: number;
  rot: number;
};

export const SCENE_ITEMS: SceneWorldItem[] = [
  {
    id: "s1-text-helpers",
    scene: 1,
    type: "text",
    title: "HELPERS",
    x: -360,
    y: -220,
    z: 0,
    rot: -6
  },
  {
    id: "s1-text-coop",
    scene: 1,
    type: "text",
    title: "COOPERATIVE",
    x: 360,
    y: 210,
    z: -320,
    rot: 5
  },
  {
    id: "s1-card-model",
    scene: 1,
    type: "card",
    title: "A cooperative, not an agency",
    eyebrow: "SYSTEM MODEL",
    body: "Helpers.ie is a growth system for microbusinesses. It does not charge first and optimize later. It builds the path before asking for a share.",
    footerLeft: "MEMBER STRUCTURE",
    footerRight: "NO RETAINER",
    emphasis: "accent",
    x: -520,
    y: -40,
    z: -760,
    rot: -8
  },
  {
    id: "s1-card-aligned",
    scene: 1,
    type: "card",
    title: "Aligned by design",
    eyebrow: "GROWTH LOGIC",
    body: "The cooperative grows when members grow. Client flow, process quality, and contribution are linked inside one shared system.",
    footerLeft: "SHARED UPSIDE",
    footerRight: "COOP LOGIC",
    emphasis: "accent2",
    x: 80,
    y: 140,
    z: -980,
    rot: 9
  },
  {
    id: "s1-card-fit",
    scene: 1,
    type: "card",
    title: "Built for real operators",
    eyebrow: "GOOD FIT",
    body: "For microbusinesses with delivery capacity, local service logic, and the discipline to grow through visible work.",
    footerLeft: "MICROBUSINESS",
    footerRight: "DELIVERY FIRST",
    emphasis: "neutral",
    x: 560,
    y: -120,
    z: -1220,
    rot: -7
  },

  {
    id: "s2-text-upfront",
    scene: 2,
    type: "text",
    title: "NO UPFRONT",
    x: -320,
    y: -240,
    z: -2200,
    rot: -4
  },
  {
    id: "s2-text-flow",
    scene: 2,
    type: "text",
    title: "CLIENT FLOW",
    x: 370,
    y: 210,
    z: -2520,
    rot: 6
  },
  {
    id: "s2-card-entry",
    scene: 2,
    type: "card",
    title: "No upfront acquisition cost",
    eyebrow: "ENTRY MODEL",
    body: "The cooperative determines, designs, and funds the client supply path before asking the business to return a share from completed work.",
    footerLeft: "FUNDED SETUP",
    footerRight: "AFTER DELIVERY",
    emphasis: "accent",
    x: -600,
    y: 10,
    z: -2860,
    rot: 8
  },
  {
    id: "s2-card-capacity",
    scene: 2,
    type: "card",
    title: "Designed around real capacity",
    eyebrow: "FLOW DESIGN",
    body: "Client supply is shaped around business type, service constraints, and the ability to serve without operational collapse.",
    footerLeft: "CAPACITY MATCH",
    footerRight: "NO CHAOS",
    emphasis: "accent2",
    x: 10,
    y: 180,
    z: -3100,
    rot: -8
  },
  {
    id: "s2-card-stable",
    scene: 2,
    type: "card",
    title: "Stable flow over random leads",
    eyebrow: "OPERATIONAL INTENT",
    body: "The goal is not noise. The goal is a supply process that a business can actually absorb, deliver, and grow from.",
    footerLeft: "CLIENT SUPPLY",
    footerRight: "CONTROLLED LOAD",
    emphasis: "neutral",
    x: 610,
    y: -120,
    z: -3340,
    rot: 7
  },

  {
    id: "s3-text-process",
    scene: 3,
    type: "text",
    title: "PROCESS",
    x: -330,
    y: -220,
    z: -4400,
    rot: -5
  },
  {
    id: "s3-text-visible",
    scene: 3,
    type: "text",
    title: "VISIBLE WORK",
    x: 360,
    y: 210,
    z: -4720,
    rot: 5
  },
  {
    id: "s3-card-visible",
    scene: 3,
    type: "card",
    title: "Work must become visible",
    eyebrow: "PROCESS DESIGN",
    body: "Everything a business touches during the working day, and the reason for that action, can be captured as part of a shared operation map.",
    footerLeft: "OPERATION MAP",
    footerRight: "DAILY WORK",
    emphasis: "accent",
    x: -580,
    y: -10,
    z: -5080,
    rot: 8
  },
  {
    id: "s3-card-touch",
    scene: 3,
    type: "card",
    title: "Touch, reason, sequence",
    eyebrow: "DOCUMENTATION",
    body: "Repeated actions, service steps, handoffs, and resource use become visible nodes inside a process model that everyone can understand.",
    footerLeft: "NODE LOGIC",
    footerRight: "SHARED MODEL",
    emphasis: "accent2",
    x: 10,
    y: 170,
    z: -5310,
    rot: -8
  },
  {
    id: "s3-card-matters",
    scene: 3,
    type: "card",
    title: "Visibility before improvement",
    eyebrow: "WHY IT MATTERS",
    body: "If work is invisible, improvement stays abstract. Helpers.ie turns real operations into something teachable, measurable, and redesignable.",
    footerLeft: "CLEAR SYSTEM",
    footerRight: "IMPROVEABLE WORK",
    emphasis: "neutral",
    x: 590,
    y: -120,
    z: -5560,
    rot: 8
  },

  {
    id: "s4-text-quality",
    scene: 4,
    type: "text",
    title: "QUALITY",
    x: -340,
    y: -220,
    z: -6600,
    rot: -4
  },
  {
    id: "s4-text-certify",
    scene: 4,
    type: "text",
    title: "CERTIFY",
    x: 370,
    y: 220,
    z: -6920,
    rot: 5
  },
  {
    id: "s4-card-node",
    scene: 4,
    type: "card",
    title: "Improve the node, not the slogan",
    eyebrow: "PROCESS UPDATE",
    body: "Specific parts of the operation map are modified through the simplest updates that can realistically be introduced into production.",
    footerLeft: "PRACTICAL CHANGE",
    footerRight: "REAL ADOPTION",
    emphasis: "accent",
    x: -600,
    y: -20,
    z: -7280,
    rot: 7
  },
  {
    id: "s4-card-standard",
    scene: 4,
    type: "card",
    title: "Every change is linked to a standard",
    eyebrow: "CERTIFICATION LOGIC",
    body: "A process designer connects each proposed modification to certification logic associated with a higher quality standard for that process node.",
    footerLeft: "HIGHER STANDARD",
    footerRight: "DESIGN REVIEW",
    emphasis: "accent2",
    x: 40,
    y: 180,
    z: -7500,
    rot: -8
  },
  {
    id: "s4-card-learning",
    scene: 4,
    type: "card",
    title: "Easier to teach, easier to adopt",
    eyebrow: "LEARNING MODEL",
    body: "This creates a shared logic for analysis, education, agreement, and implementation across the cooperative.",
    footerLeft: "SHARED LEARNING",
    footerRight: "QUALITY PATH",
    emphasis: "neutral",
    x: 620,
    y: -130,
    z: -7740,
    rot: 8
  },

  {
    id: "s5-text-measure",
    scene: 5,
    type: "text",
    title: "MEASURE",
    x: -350,
    y: -230,
    z: -8800,
    rot: -5
  },
  {
    id: "s5-text-usecase",
    scene: 5,
    type: "text",
    title: "USE CASE",
    x: 350,
    y: 220,
    z: -9120,
    rot: 6
  },
  {
    id: "s5-card-before-after",
    scene: 5,
    type: "card",
    title: "Compare before and after",
    eyebrow: "AFTER IMPLEMENTATION",
    body: "Once an update is introduced into real work, the cooperative compares process effectiveness before and after the change.",
    footerLeft: "BEFORE / AFTER",
    footerRight: "EFFECT CHECK",
    emphasis: "accent",
    x: -600,
    y: -10,
    z: -9480,
    rot: 8
  },
  {
    id: "s5-card-published",
    scene: 5,
    type: "card",
    title: "Proven changes are shared",
    eyebrow: "PUBLISHED RESULT",
    body: "The full use case, together with the measured result, becomes visible to other members of the cooperative.",
    footerLeft: "MEMBER ACCESS",
    footerRight: "PUBLISHED LOGIC",
    emphasis: "accent2",
    x: 30,
    y: 170,
    z: -9720,
    rot: -8
  },
  {
    id: "s5-card-compounds",
    scene: 5,
    type: "card",
    title: "Improvement compounds",
    eyebrow: "KNOWLEDGE MODEL",
    body: "What works in one operation can inform the next. The system grows by publishing practical evidence, not hidden tricks.",
    footerLeft: "SHARED MEMORY",
    footerRight: "COOP INTELLIGENCE",
    emphasis: "neutral",
    x: 620,
    y: -130,
    z: -9960,
    rot: 8
  },

  {
    id: "s6-text-membership",
    scene: 6,
    type: "text",
    title: "MEMBERSHIP",
    x: -350,
    y: -230,
    z: -11000,
    rot: -4
  },
  {
    id: "s6-text-commission",
    scene: 6,
    type: "text",
    title: "COMMISSION",
    x: 360,
    y: 220,
    z: -11320,
    rot: 5
  },
  {
    id: "s6-card-after-value",
    scene: 6,
    type: "card",
    title: "Contribution begins after value",
    eyebrow: "CONTRIBUTION MODEL",
    body: "Membership is voluntary and contribution happens after the cooperative has already done real work for the member business.",
    footerLeft: "VOLUNTARY",
    footerRight: "AFTER VALUE",
    emphasis: "accent",
    x: -650,
    y: -80,
    z: -11660,
    rot: 8
  },
  {
    id: "s6-card-lowers",
    scene: 6,
    type: "card",
    title: "Contribution lowers commission",
    eyebrow: "COMMISSION LOGIC",
    body: "The more strongly a member supports the cooperative, the lower the ongoing commission expected from completed deals.",
    footerLeft: "REDUCED SHARE",
    footerRight: "MEMBER SUPPORT",
    emphasis: "accent2",
    x: -80,
    y: 180,
    z: -11880,
    rot: -7
  },
  {
    id: "s6-card-tier-365",
    scene: 6,
    type: "card",
    title: "€365 / year -> 10%",
    eyebrow: "CONTRIBUTION LEVEL",
    body: "Entry contribution for members who want to participate while keeping the cooperative relationship active and visible.",
    footerLeft: "ANNUAL LEVEL",
    footerRight: "10% COMMISSION",
    emphasis: "neutral",
    x: 540,
    y: -130,
    z: -12120,
    rot: 8
  },
  {
    id: "s6-card-tier-3650",
    scene: 6,
    type: "card",
    title: "€3,650 / year -> 1%",
    eyebrow: "CONTRIBUTION LEVEL",
    body: "Higher support reduces the expected share dramatically and signals stronger long-term commitment to the system.",
    footerLeft: "ANNUAL LEVEL",
    footerRight: "1% COMMISSION",
    emphasis: "accent2",
    x: -300,
    y: -250,
    z: -12360,
    rot: 6
  },
  {
    id: "s6-card-tier-36500",
    scene: 6,
    type: "card",
    title: "€36,500 / year -> 0%",
    eyebrow: "CONTRIBUTION LEVEL",
    body: "Maximum contribution eliminates ongoing commission and turns competitive priority toward contribution history and paid years.",
    footerLeft: "ANNUAL LEVEL",
    footerRight: "0% COMMISSION",
    emphasis: "accent",
    x: 240,
    y: 260,
    z: -12620,
    rot: -6
  },

  {
    id: "s7-text-priority",
    scene: 7,
    type: "text",
    title: "PRIORITY",
    x: -350,
    y: -220,
    z: -13200,
    rot: -4
  },
  {
    id: "s7-text-visibility",
    scene: 7,
    type: "text",
    title: "VISIBILITY",
    x: 360,
    y: 220,
    z: -13520,
    rot: 5
  },
  {
    id: "s7-card-contribution",
    scene: 7,
    type: "card",
    title: "Contribution changes visibility",
    eyebrow: "TRUST LOGIC",
    body: "The faster the returned share comes back to the cooperative, the stronger the internal visibility of the business becomes.",
    footerLeft: "TIMING SIGNAL",
    footerRight: "INTERNAL WEIGHT",
    emphasis: "accent",
    x: -620,
    y: -60,
    z: -13860,
    rot: 8
  },
  {
    id: "s7-card-quality",
    scene: 7,
    type: "card",
    title: "Quality affects future flow",
    eyebrow: "SERVICE LOGIC",
    body: "Businesses that serve well, avoid destructive client conflict, and operate transparently receive stronger future support.",
    footerLeft: "SERVICE QUALITY",
    footerRight: "FLOW PRIORITY",
    emphasis: "accent2",
    x: -40,
    y: 180,
    z: -14080,
    rot: -8
  },
  {
    id: "s7-card-consistency",
    scene: 7,
    type: "card",
    title: "Reliability compounds",
    eyebrow: "CONSISTENCY MODEL",
    body: "Visibility is shaped by quality, transparency, timing, contribution, and long-term consistency inside the cooperative.",
    footerLeft: "TRUST HISTORY",
    footerRight: "MEMBER PRIORITY",
    emphasis: "neutral",
    x: 560,
    y: -130,
    z: -14320,
    rot: 8
  },
  {
    id: "s7-card-paid-years",
    scene: 7,
    type: "card",
    title: "Paid years can matter",
    eyebrow: "MAX LEVEL",
    body: "At the highest contribution level, competitive priority can also depend on the number of years a member has sustained that level.",
    footerLeft: "PAID YEARS",
    footerRight: "PRIORITY EDGE",
    emphasis: "accent2",
    x: 180,
    y: 270,
    z: -14560,
    rot: -7
  },

  {
    id: "s8-text-stay",
    scene: 8,
    type: "text",
    title: "STAY",
    x: -340,
    y: -230,
    z: -15400,
    rot: -5
  },
  {
    id: "s8-text-network",
    scene: 8,
    type: "text",
    title: "NETWORK",
    x: 350,
    y: 220,
    z: -15720,
    rot: 6
  },
  {
    id: "s8-card-remain",
    scene: 8,
    type: "card",
    title: "Non-payment does not remove you",
    eyebrow: "MEMBERSHIP STATUS",
    body: "A member who does not contribute can remain inside the cooperative, continue observing, and stay connected to the network.",
    footerLeft: "NO EXPULSION",
    footerRight: "STILL INSIDE",
    emphasis: "accent",
    x: -600,
    y: -40,
    z: -16080,
    rot: 8
  },
  {
    id: "s8-card-access",
    scene: 8,
    type: "card",
    title: "Learn without active priority",
    eyebrow: "NETWORK ACCESS",
    body: "Members may still communicate with others, follow published use cases, and understand how solutions are being developed.",
    footerLeft: "USE CASE ACCESS",
    footerRight: "NETWORK VIEW",
    emphasis: "accent2",
    x: 30,
    y: 170,
    z: -16320,
    rot: -8
  },
  {
    id: "s8-card-effort",
    scene: 8,
    type: "card",
    title: "Effort follows contribution",
    eyebrow: "RESOURCE ALLOCATION",
    body: "The cooperative directs active growth effort toward members who sustain the system through contribution and reliable participation.",
    footerLeft: "COOP EFFORT",
    footerRight: "ACTIVE FOCUS",
    emphasis: "neutral",
    x: 620,
    y: -120,
    z: -16560,
    rot: 8
  },

  {
    id: "s9-text-apply",
    scene: 9,
    type: "text",
    title: "APPLY",
    x: -330,
    y: -230,
    z: -17600,
    rot: -5
  },
  {
    id: "s9-text-join",
    scene: 9,
    type: "text",
    title: "JOIN",
    x: 360,
    y: 220,
    z: -17920,
    rot: 6
  },
  {
    id: "s9-card-ready",
    scene: 9,
    type: "card",
    title: "Built for businesses ready to grow visibly",
    eyebrow: "WHO THIS IS FOR",
    body: "Helpers.ie is for microbusinesses that can serve more clients, record real work, and improve through shared operational logic.",
    footerLeft: "READY TO SCALE",
    footerRight: "VISIBLE WORK",
    emphasis: "accent",
    x: -600,
    y: -40,
    z: -18280,
    rot: 8
  },
  {
    id: "s9-card-selective",
    scene: 9,
    type: "card",
    title: "Not every business is a fit",
    eyebrow: "SELECTIVE ENTRY",
    body: "The cooperative works best where service quality, delivery discipline, and operational honesty are already possible.",
    footerLeft: "SELECTIVE MODEL",
    footerRight: "QUALITY FIRST",
    emphasis: "accent2",
    x: 20,
    y: 180,
    z: -18520,
    rot: -8
  },
  {
    id: "s9-card-apply",
    scene: 9,
    type: "card",
    title: "Apply to join the cooperative",
    eyebrow: "NEXT STEP",
    body: "Enter the system if you are ready for funded client supply, visible operations, and growth tied to real delivery.",
    footerLeft: "HELPERS.IE",
    footerRight: "APPLY NOW",
    emphasis: "neutral",
    x: 620,
    y: -120,
    z: -18760,
    rot: 8
  }
];
